language: python
branches:
    only:
        - master
        - dogfood
services:
  - postgres
python:
  - "2.7"
env:
  - DB=sqlite
  - DB=postgres
install:
  - sh -c "if [ $DB = postgres ]; then pip install psycopg2; fi"
  - python setup.py install
before_script:
  - sh -c "if [ $DB = postgres ]; then psql -c 'CREATE DATABASE haas_travis;' -U postgres; fi"
  - sh -c "if [ $DB = postgres ]; then cp ci/testsuite.cfg.postgres testsuite.cfg; fi"
script: "py.test tests/unit tests/stress.py"
